fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    python: "git@github.com:stankevich/puppet-python.git"
    apache: "git://github.com/puppetlabs/puppetlabs-apache.git"
    concat:
      repo: "git://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "1.1.1"
    postgresql:
      repo: "https://github.com/puppetlabs/puppetlabs-postgresql.git"
      ref: "4.0.0"
    nodejs: "git://github.com/puppetlabs/puppetlabs-nodejs.git"
    memcached: "https://github.com/saz/puppet-memcached.git"
  symlinks:
    reviewboard: "#{source_dir}"
