fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    # note, this isn't open yet :(
    virtualenv: "git@github.com:coxmediagroup/puppet-virtualenv.git"
  symlinks:
    reviewboard: "#{source_dir}"
