fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    # note, this isn't open yet :(
    virtualenv: "git@github.com:coxmediagroup/puppet-virtualenv.git"
    python: "git@github.com:coxmediagroup/puppet-python.git"
    yum: "git@github.com:coxmediagroup/puppet-yum.git"
    apache: "git://github.com/puppetlabs/puppetlabs-apache.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    postgresql:
      repo: "https://github.com/jantman/puppetlabs-postgresql.git"
      ref: '3.2.0+PR-450'
    mysql: "git://github.com/puppetlabs/puppetlabs-mysql.git"
    nodejs: "git://github.com/puppetlabs/puppetlabs-nodejs.git"
  symlinks:
    reviewboard: "#{source_dir}"
