fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    # note, this isn't open yet :(
    virtualenv: "git@github.com:coxmediagroup/puppet-virtualenv.git"
    python: "git@github.com:coxmediagroup/puppet-python.git"
    apache: "git://github.com/puppetlabs/puppetlabs-apache.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    postgresql: "git://github.com/puppetlabs/puppetlabs-postgresql.git"
    mysql: "git://github.com/puppetlabs/puppetlabs-mysql.git"
  symlinks:
    reviewboard: "#{source_dir}"
